# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='New Dictionary', max_length=60)),
                ('input_lang', models.CharField(default='En', max_length=6)),
                ('output_lang', models.CharField(default='Ru', max_length=6)),
                ('translations', models.TextField(blank=True, default='[]')),
                ('file', models.FileField(blank=True, upload_to='files')),
                ('time_before_translation', models.IntegerField(default=50)),
                ('time_between_translations', models.IntegerField(default=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
